enableGlobalCache: true
nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.3.1.cjs
pnpMode: loose

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
