Neos:
  Flow:
    mvc:
      routes:
        'Shel.Neos.Terminal':
          position: 'start'

    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'Shel.Neos.Terminal:Commands':
                pattern: ControllerObjectName
                patternOptions:
                  controllerObjectNamePattern: 'Shel\Neos\Terminal\Controller\.*'

  Neos:
    Ui:
      resources:
        javascript:
          Shel.Neos.Terminal:Terminal:
            resource: resource://Shel.Neos.Terminal/Public/Assets/Plugin.js
        stylesheets:
          Shel.Neos.Terminal:Terminal:
            resource: resource://Shel.Neos.Terminal/Public/Assets/Plugin.css

      frontendConfiguration:
        'Shel.Neos.Terminal:Terminal':
          enabled: false
          welcomeMessage: 'Shel.Neos.Terminal:Main:welcome'
          registrationKey: ''
          theme:
            contentStyle:
              color: '#00adee'
            styleEchoBack: 'fullInherit'
            promptLabelStyle:
              color: '#ff8700'
            inputTextStyle:
              color: '#ffffff'
          commands:
            eel:
              description: 'Shel.Neos.Terminal:Main:command.eel.description'
              usage: 'eel <string>'
              endPoint: '/neos/shel-neos-terminal/evaluateeelexpression'
              useNodeContext: true
              argumentName: 'expression'
            flushCache:
              description: 'Shel.Neos.Terminal:Main:command.flushCache.description'
              usage: 'flushCache [<string>]'
              endPoint: '/neos/shel-neos-terminal/flushcache'
              useNodeContext: false
              argumentName: 'cacheIdentifier'

    userInterface:
      translation:
        autoInclude:
          Shel.Neos.Terminal: ['Main']
