Neos:
  Neos:
    Ui:
      resources:
        javascript:
          Shel.Neos.Terminal:Terminal:
            resource: resource://Shel.Neos.Terminal/Public/Assets/Plugin.js
        stylesheets:
          Shel.Neos.Terminal:Terminal:
            resource: resource://Shel.Neos.Terminal/Public/Assets/Plugin.css

      frontendConfiguration:
        'Shel.Neos.Terminal:Terminal':
          enabled: false
          welcomeMessage: 'Shel.Neos.Terminal:Main:welcome'
          registrationKey:
            id: ''
            signature: ''
          getCommandsEndPoint: '/neos/shel-neos-terminal/getcommands'
          invokeCommandEndPoint: '/neos/shel-neos-terminal/invokecommand'
          theme:
            contentStyle:
              color: '#00adee'
            styleEchoBack: 'fullInherit'
            promptLabelStyle:
              color: '#ff8700'
            inputTextStyle:
              color: '#ffffff'
            messageStyle:
              white-space: 'pre-wrap'

    userInterface:
      translation:
        autoInclude:
          Shel.Neos.Terminal: ['Main']
