name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        neosVersion:
          - '4.3'
          - '5.3'
          - '7.3'

    name: 'Terminal ${{ matrix.neosVersion }} test'

    env:
      NEOS_TARGET_VERSION: ${{matrix.neosVersion}}
      FLOW_CONTEXT: Testing
      FLOW_FOLDER: ../neos-base-distribution

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4

    - name: Update Composer
      run: |
        sudo composer self-update
        composer --version

    # Directory permissions for .composer are wrong, so we remove the complete directory
    # https://github.com/actions/virtual-environments/issues/824
    - name: Delete .composer directory
      run: |
        sudo rm -rf ~/.composer

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.composer/cache
        key: dependencies-composer-${{ hashFiles('composer.json') }}

    - name: Prepare Flow distribution
      run: |
        git clone https://github.com/neos/neos-base-distribution.git -b ${NEOS_TARGET_VERSION} ${FLOW_FOLDER}
        cd ${FLOW_FOLDER}
        composer require --no-update --no-interaction shel/neos-terminal

    - name: Install distribution
      run: |
        cd ${FLOW_FOLDER}
        composer install --no-interaction --no-progress
        rm -rf Packages/Plugins/Shel.Neos.Terminal
        cp -r ../Shel.Neos.Terminal Packages/Plugins/Shel.Neos.Terminal

    - name: Run Functional tests
      run: |
        cd ${FLOW_FOLDER}
        bin/phpunit --colors -c Build/BuildEssentials/PhpUnit/FunctionalTests.xml Packages/Plugins/Shel.Neos.Terminal/Tests/Functional/*
